#!/bin/sh

########################################################################
#
#	a012.sh
#	This demo starts iCserver, 3 iCboxes and the control program
#	'a012' which is generated by iCmake a012.ic
#
#	All digital inputs X0.0 to X0.7 and analog inputs IB1 and IW2
#	act directly on the corresponding outputs.
#
#	IX0 is preset to 0x33, IB1 to 50 and IW2 to -10000.
#	The ranges of W2 have been changed from the default 0 to 100.
#
#	Stop the demo with ctrl-C
#
########################################################################

iCserver 'iCbox X0 0x33' 'iCbox B1 50' 'iCbox -R -32568 -r 32567 W2 -10000' a012
