#!/bin/sh

########################################################################
#
#	bar2.sh
#	This demo starts iCserver, 9 iCboxes and the control program
#	'bar2' which is generated by iCmake bar2.ic
#
#	iCbox IB4 to IB7 are analog inputs, each initialized to 1.
#	This sets the clocking speed of the running lights on QX0 to QX3
#	to 50 ms.
#
#	By changing the input sliders IB4 to IB7 the clocking speed
#	on QX0 is set to IB4 * 50 ms, QX1 is set to IB5 * 50 ms etc.
#	A value of 0 on inputs IB4 to IB7 lets you clock the running
#	lights manually via inputs IX0.0 to IX3.0.
#
#	Outputs QX8.0 to QX8.3 indicate the direction of the running
#	lights on QX0 to QX4 - just to show a bit of internal logic.
#
#	Stop the demo with ctrl-C
#
########################################################################

iCserver 'iCbox X0 X1 X2 X3 B4=1 B5=1 B6=1 B7=1 X8' 'bar2 -d1000'
