#!/bin/sh

########################################################################
#
#	demo.sh
#	This demo starts iCserver, 4 iCboxes and the control program
#	'demo' which is generated by iCmake demo.ic
#
#	Inputs I0 to I7 can be taken from iCbox X0 to X3 by the
#	settings of IX3.6 and IX3.7 on iCbox X3 (default is IX0.0 to IX0.7)
#
#	see 'demo.ic' for the logic
#
#	Stop the demo with ctrl-C
#
########################################################################

iCserver 'iCbox X0 X1 X2 X3' 'demo -d1000'
