#!/bin/sh

########################################################################
#
#	sort32i.sh
#
#	This demo starts iCserver and the control program
#	'sort32i' which is generated by iCmake sort32i.ic
#	I/Os with iCbox is autovivyfied with the -a option of iCserver
#
#	Stop the demo with ctrl-C
#
########################################################################

iCserver -kra sort32i
