#!/bin/sh

########################################################################
#
#	zuelke.sh
#
#	Zuelke Beispiel - Luzern 19.Apil.2005
#	This demo starts iCserver and the control program
#	'zuelke' which is generated by iCmake zuelke.ic
#	I/Os with iCbox is autovivyfied with the -a option of iCserver
#
#	Stop the demo with ctrl-C
#
########################################################################

iCserver -kra zuelke
