#!/usr/bin/perl
########################################################################
#
# $Id: gaIdke-post-commit 1.7 $
# $IdBlockFurtherExpansion$
#
#  Copyright © 2016 John E Wulff <immediatec@gmail.com>
#  SPDX-License-Identifier: MIT
#
# Filters and hooks to implement 'Automatic GIT $Id: Keyword Expansion'
#
# post-commit:
#         Obtain the list of files which have been updated with an
#         incremented <rev> in pre-commit from .gitSmudgeList. Execute
#         'git checkout HEAD' to call smudge so the file in the working
#         directory will have a $Id with an incremented <rev> followed
#         by the commit hash, the author commit date and the author name.
#         Also remove the backup file here.
#
#         The backup could be used here to 'touch -r' the checked out file
#         to leave the modify date of the file unchanged after git commit,
#         although it has actually been modified. This would be similar
#         to the RCS 'co -M' option. Since there is no access to options
#         in git commit and the git philosophy is to always modify dates
#         on checkout it was felt best to not touch the checked out file.
#         This way a make immediately after commit will bring the updated
#         <rev> Id's into the binaries, if $Ids are stored in binaries.
#
########################################################################

if (open SMUDGE, ".gitSmudgeList") {	# ignore if pre-commit had no files with $Ids
    while (<SMUDGE>) {
	($path, $remainder) = split " ", $_, 2;
	qx(git checkout HEAD $path; rm -f "$path.gaidke");
    }
    close SMUDGE;
    qx(rm -f .gitSmudgeList);		# do only once at end of commit
}
