#!/usr/bin/perl
########################################################################
#
# $Id: gaIdke-prepare-commit-msg 1.7 $
# $IdBlockFurtherExpansion$
#
#  Copyright © 2016 John E Wulff <immediatec@gmail.com>
#  SPDX-License-Identifier: MIT
#
# Filters and hooks to implement 'Automatic GIT $Id: Keyword Expansion'
#
# prepare-commit-msg:
#         Obtain the list of files which have been updated with an
#         incremented <ver> in pre-commit from .gitSmudgeList. Each
#         smudgeLine in .gitSmudgeList is formatted as follows by pre-commit:
#
#             <path> <ver>
#           or
#             <path> <ver> <- <previous_filename>
#
#         These lines preceded by '    Id: ' are added before the first
#         comment of the new commit message. No lines are added for any
#         files in the commit, which do not have a $Id string.
#
# To activate this filter put a symlink in .git/hooks to this file.
#
########################################################################

$commitMsg = shift;
if (open SMUDGE, ".gitSmudgeList") {	# ignore if pre-commit had no files with $Ids
    qx(mv -f "$commitMsg" "$commitMsg.gaidke");
    open IN, "$commitMsg.gaidke" or die "Cannot open '$commitMsg.gaidke': $!";
    open OUT, ">$commitMsg" or die "Cannot create '$commitMsg': $!";
    while (<IN>) {
	if (not $smudgeLine and m/^\s*#/) {
	    print OUT "\n";
	    while (defined($smudgeLine = <SMUDGE>)) {
		print OUT "    Id: $smudgeLine";
	    }
	    $smudgeLine = "EOF";	# use as flag to block repeats
	}
	print OUT;
    }
    if (not $smudgeLine) {	# in case there are no comments - unlikely but defensive
	print OUT "\n";
	while (defined($smudgeLine = <SMUDGE>)) {
	    print OUT "    Id: $smudgeLine";
	}
    }
    close OUT;
    close IN;
    close SMUDGE;
    qx(rm -f "$commitMsg.gaidke");
}
