#!/usr/bin/perl
########################################################################
#
#	iC generic Demo Box
#	adapted from
#	Example 14-1 Simple UI Code
#	Sriram Srinivasan: Advanced Perl p. 224
#
########################################################################

use Tk;					# Slurp the module in
use Msg;
use strict;
#use Devel::Peek 'Dump';		# ZZZ

my @inputs;
my @outputs;
my $inByte =	0;		# initialize to a number for correct OR
my $outByte =	0;		# initialize to a number for correct XOR

my @indices;			# initialize on startup
my @masks =	(1, 2, 4, 8, 16, 32, 64, 128);
my @invert =	(1, 0);		# invert logic sense

########################################################################
#
#	Initialization
#
########################################################################

my $named = $0; $named =~ s#.*[/\\]##;
format STDERR =
Usage:	@<<<<<< [-teh] [-s <host>] [-p <port>] [<unitID>]
	$named
	-s host	ID of server (default 'localhost')
	-p port	service port of server (default '8778')
	unitID	default is 'X0'
	-t	trace debug messages
	-h	help, ouput this Usage text only
$Id: DemoBox,v 1.25 2001/01/23 23:04:13 jw Exp $
.

use vars qw($opt_t $opt_e $opt_s $opt_p $opt_h);
require "getopts.pl";
&Getopts('tes:p:h');			# sets $opt_h if -h etc

if ($opt_h) {
    write STDERR; exit 0;	# -h, ouput Usage only
}

# initialize array @indices

for my $mask (0 .. 255) {
    my @tmp;
    for my $index (0 .. 7) {
	if ($mask & $masks[$index]) {
	    push @tmp, $index;
	}
    }
    $indices[$mask] = [ @tmp ];
}
# for my $mask (0 .. 255) { print "$mask\t[ @{$indices[$mask]} ],\n"; }

########################################################################
#
#	Connect to server
#
########################################################################

my $host = defined $opt_s ? $opt_s : 'localhost';
my $port = defined $opt_p ? $opt_p : 8778;
my $unitID = (@ARGV >= 1) ? $ARGV[0] : 'X0';

my $conn = Msg->connect($host, $port, \&rcvd_msg_from_server);
die "Client could not connect to $host:$port\n" unless $conn;

print "Connection $unitID at client.\n";
$conn->send_now($unitID);		# register I/O

########################################################################
#
#	Create main window and optional Exit button
#
########################################################################

my $mainWindow = MainWindow->new();
$mainWindow->title("iC");
$mainWindow->Label(-text => "iC Demo Box")->pack;

$mainWindow->Button(-text    => "Exit",
		    -command => sub { exit; },
		   )->pack(-side   => 'bottom', 
			   -expand => 1,
			   -fill   => 'x',
			  ) if $opt_e;

########################################################################
#
#	Generate an input and an output frame
#
########################################################################

my $inLabel = "input";
my $outLabel = "output";
if ($unitID !~ /^X/) {
    $inLabel = "in I$unitID";
    $outLabel = "out Q$unitID";
}

my $inFrame  = $mainWindow->Frame(-label       => $inLabel,
				  -relief      => 'groove',
				  -borderwidth => 2,
				 )->pack(-side   => 'left', 
				         -expand => 'y',
				         -fill   => 'y',
				        );

my $outFrame = $mainWindow->Frame(-label       => $outLabel,
				  -relief      => 'groove',
				  -borderwidth => 2,
				 )->pack(-side   => 'right', 
				         -expand => 'y',
				         -fill   => 'y',
				        );

########################################################################
#
#	Generate 8 input checkbuttons and 8 output checkbuttons
#
########################################################################

if ($unitID =~ /^X/) {
    for my $index (0 .. 7) {
	my $input = "I$unitID.$index";
	my $makeCheckbutton = "\
	    \$inFrame->Checkbutton(\
		-text        => \$input,\
		-variable    => \\\$inputs[\$index],\
		-selectcolor => 'green',\
		-command     => sub {\
				     if (\$inputs[$index]) {\
					 \$inByte |= $masks[$index];	# set bit\
				     } else {\
					 \$inByte &= ~$masks[$index];	# clear bit\
				     }\
				     print \"I$unitID.$index --> \$inputs[$index] (\$inByte)\\n\" if \$opt_t;\
				     \$conn->send_now(\"\$inByte\");\
				    },\
	    )->pack(-side   => 'top',\
		    -expand => 1,\
	    );\
	";
	eval $makeCheckbutton;
	print $@;
    }

    for my $index (0 .. 7) {
	my $output = "Q$unitID.$index";
	my $makeCheckbutton = "\
	    \$outFrame->Checkbutton(\
		-text        => \$output,\
		-variable    => \\\$outputs[\$index],\
		-selectcolor => 'red',\
#		-state       => 'disabled',\
		-takefocus   => 0,\
		-command     => sub {\
				     print \"Inverting output $index on Q$unitID\\n\" if \$opt_t;\
				     \$outputs[$index] = \$invert[\$outputs[$index]];\
				    },\
	    )->pack(-side   => 'top',\
		    -expand => 1,\
	    );\
	";
	eval $makeCheckbutton;
	print $@;
	$outputs[$index] = 0;
    }
}

########################################################################
#
#	Generate 1 input analog scale and 1 output analog scale
#
########################################################################

elsif ($unitID =~ /^[BW]/) {

	my $input = "I$unitID";

	    $inFrame->Scale(
#		-label       => $input,
		-from        => 0,
		-to          => 100,
		-length      => 170,
		-variable    => \$inByte,
		-command     => sub {
				     if (length $inByte) {
					 print "I$unitID --> $inByte\n" if $opt_t;
					 $conn->send_now("$inByte");
				     }
				    },
	    )->pack(-side   => 'top',
		    -expand => 1,
	    );

	my $output = "Q$unitID";

	    $outFrame->Scale(
#		-label       => $output,
		-from        => 0,
		-to          => 100,
		-length      => 170,
		-variable    => \$outputs[0],
		-state       => 'disabled',
		-takefocus   => 0,
	    )->pack(-side   => 'top',
		    -expand => 1,
	    );
	$outputs[0] = 0;
}

########################################################################
#
#	Register read events
#
########################################################################

else {
    die "DemoBox $unitID could not be made\n";
}

$mainWindow->fileevent($conn->{sock}, 'readable', sub { Msg->event_loop(1); });

########################################################################
#
#	Sit in an infinite loop dispatching incoming events.
#
########################################################################

MainLoop;

########################################################################
#
#	Receive message from server - adjust outputs
#
########################################################################

sub rcvd_msg_from_server {
    my ($conn, $msg, $err) = @_;
    if (defined $msg) {
        my $len = length ($msg);
#	print "($len)$msg\n";
	if ($len == 0) {
	    $conn->disconnect();
	    print "DemoBox $unitID disconnected by server\n";
	    exit;
	}
	if ($unitID =~ /^X/) {
	    if ($msg eq "R") {
		for my $index (0 .. 7) {
		    if ($outputs[$index]) {
			print "init Q$unitID.$index 0 <-- 1\n" if $opt_t;
			$outputs[$index] = 0;
		    }
		}
		$outByte = 0;
		if ($inByte) {
		    print "send I$unitID 0 --> $inByte\n" if $opt_t;
		    $conn->send_now("$inByte");
		}
	    } elsif ($msg =~ /^\d+$/) {
		my $mask = $outByte ^ $msg;	# $outByte initialized to a number for correct XOR
#		Dump $mask;			# ZZZ
#		printf("Q%s %02x %02x\n", $unitID, $msg, $mask) if $opt_t;
		for my $index (@{$indices[$mask]}) {
		    my $value = ($msg & $masks[$index]) ? 1 : 0;
		    print "Q$unitID.$index $value <-- $outputs[$index] ($msg)\n" if $opt_t;
		    $outputs[$index] = $value;
		}
		$outByte = $msg;
	    } else {
		print "$unitID received spurious message: '$msg'\n";
	    }
	} elsif ($unitID =~ /^[BW]/) {
	    if ($msg eq "R") {
		if ($outputs[0]) {
		    print "init Q$unitID 0 <-- $outputs[0]\n" if $opt_t;
		    $outputs[0] = 0;
		}
		if (length $inByte and $inByte) {
		    print "send I$unitID 0 --> $inByte\n" if $opt_t;
		    $conn->send_now("$inByte");
		}
	    } elsif ($msg =~ /^\d+$/) {
		print "Q$unitID $msg <-- $outputs[0]\n" if $opt_t;
		$outputs[0] = $msg;
	    } else {
		print "$unitID received spurious message: '$msg'\n";
	    }
	}
    }
}
