#!/usr/bin/perl
########################################################################
#
#	Example 14-1 Simple UI Code
#	Sriram Srinivasan: Advanced Perl p. 224
#
########################################################################

use Tk;					# Slurp the module in

########################################################################
#
#	Create main window
#
########################################################################

$top = MainWindow->new();
$top->title("Simple");

########################################################################
#
#	Instantiate widgets and arrange them
#
########################################################################

$label = $top->Label(
    text	=> 'hello',	# label properties
    anchor	=> 'n',		# anchor text to "north"
    relief	=> 'groove',	# border style
    width	=> 10,		# characters wide
    height	=> 3,		# characters high
);
$label->pack;	# give it a default place in the main window

########################################################################
#
#	Generate a button
#
########################################################################

$button = $top->Button(
    text	=> 'John',
    command	=> \&change_label,
);
$button->pack;	# give it a default place in the main window

########################################################################
#
#	Sit in an infinite loop dispatching incoming events.
#
########################################################################

MainLoop();

########################################################################
#
#	Callback function
#
########################################################################

sub change_label
{
    $button->cget('text') eq 'John'	   ?
	$button->configure(text => 'Helene') :
	$button->configure(text => 'John');
}
