
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[351] =
    {   0,
        0,    0,  105,  103,  101,  102,   89,  103,   47,   95,
       88,  103,   83,   84,   93,   92,   80,   91,   87,   94,
       49,   49,   81,   77,   96,   82,   97,  100,   47,   47,
       85,   86,   98,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   78,
       99,   79,   90,  101,    3,  101,   75,    0,   54,    0,
       47,   61,   70,   62,    0,    0,   59,   67,   57,   68,
       58,   69,    0,   52,    1,    2,   60,   53,   49,    0,
       49,    0,   66,   72,   74,   73,   65,   47,   47,   63,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       11,   47,   47,   47,   47,   47,   47,   19,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   64,
       71,  101,    3,   50,   76,    0,   52,   52,    0,   53,
        0,   51,   48,   56,   55,   46,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   39,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   17,   47,   47,   20,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,    0,   52,    0,   52,    0,   53,   51,
       48,   47,    0,    0,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,    4,   47,   47,    6,
        7,   47,   47,   47,   47,   13,   14,   47,   47,   18,
       47,   21,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   34,   47,   47,    0,   52,   46,
        0,   45,   47,   47,   47,   47,   47,   39,   47,    5,
       47,    8,   47,   47,   47,   47,   47,   16,   47,   47,
       47,   47,   24,   47,   47,   47,   47,   47,   47,   47,
       32,   47,   47,   36,    0,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   12,   47,   15,   41,   47,   47,
       23,   25,   26,   27,   28,   29,   47,   31,   47,   47,

       45,   47,   47,   47,   47,    8,   47,   10,   47,   47,
       47,   47,   47,   30,   47,   47,   47,   44,   43,   47,
       47,    9,   47,   41,   22,   42,   25,   31,   33,   35,
       38,   47,   40,   47,   47,   47,   47,   47,   47,   42,
       33,   35,   38,   47,   40,   47,   47,   47,   37,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   28,   28,   30,   31,
        8,    8,   32,    8,    8,   33,    8,   34,    8,    8,
       35,    8,    8,   36,   37,    8,   38,   39,    8,    8,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,    8,   54,   55,   56,   57,
       58,   59,    8,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1,    1,    2,    4,    4,    4,    4,    4,    4,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[355] =
    {   0,
        0,   71,  522,  523,   72,  523,  496,   69,    0,  495,
       67,  478,  523,  523,  493,   64,  523,   65,   63,   74,
       93,   82,  523,  523,   61,  492,   69,  523,   68,  477,
      523,  523,  490,  470,   55,   45,   75,   38,   81,   66,
      455,   72,  454,  462,   87,  443,  452,  450,  455,  523,
       55,  523,  523,  139,  523,  149,  523,  103,  523,  503,
        0,  523,  523,  523,   87,  147,  523,  523,  523,  523,
      523,  523,  487,  134,  523,  523,  523,  141,  148,  178,
      149,    0,  479,  523,  523,  523,  478,  114,  155,  523,
      182,  446,  439,  438,  450,  445,  436,  451,  438,  444,

      430,  431,  428,  428,  431,  428,  425,    0,  108,  429,
      126,  427,  141,  134,  431,  424,  147,  152,  429,  523,
      523,  212,  523,  523,  523,  203,  523,  217,  219,  523,
      181,  231,  216,  523,  523,  212,  255,  449,  448,  160,
      416,  420,  411,  419,  426,  421,  406,  415,  413,  426,
      409,  410,  422,  411,  416,  404,  164,  418,  416,  412,
      404,  410,  413,    0,  399,  403,    0,  404,  401,  391,
      389,  391,  393,  400,  386,  384,  384,  396,  386,  390,
      394,  396,  385,  234,  249,  268,  523,  240,  270,  523,
      259,  257,  291,  303,  406,  404,  380,  374,  380,  373,

      382,  373,  370,  375,  385,  375,    0,  373,  364,    0,
        0,  363,  371,  360,  367,    0,    0,  100,  359,    0,
      363,    0,  358,  358,  357,  354,  366,  356,  360,  365,
      364,  226,  353,  358,    0,  346,  358,  277,  295,  290,
      315,  309,  376,  375,  343,  354,  353,    0,  355,    0,
      347,  355,  341,  342,  347,  334,  337,    0,  344,  330,
      338,  333,    0,  341,  338,  340,  324,  333,  335,  333,
        0,  325,  328,    0,  292,  336,  335,  321,  319,  313,
      318,  330,  310,  310,    0,  318,    0,  326,  320,  321,
        0,  323,    0,    0,    0,    0,  316,  321,  314,  304,

      311,  308,  307,  287,  304,    0,  298,    0,  288,  300,
      283,  280,  297,    0,  296,  291,  289,    0,    0,  288,
      270,    0,  276,    0,    0,  283,    0,    0,  277,  264,
      258,  255,  243,  224,  221,  219,  197,  186,  173,    0,
        0,    0,    0,  155,    0,  153,  119,  111,    0,  523,
      353,  356,  360,  100
    } ;

static yyconst flex_int16_t yy_def[355] =
    {   0,
      350,    1,  350,  350,  350,  350,  350,  351,  352,  350,
      350,  353,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  352,  352,
      350,  350,  350,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  350,
      350,  350,  350,  350,  350,  350,  350,  351,  350,  351,
      352,  350,  350,  350,  353,  353,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  354,  350,  350,  350,  350,  350,  352,  352,  350,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  354,  350,  350,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  350,  350,  350,  350,  350,  350,  350,
      350,  352,  350,  350,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  350,  350,  352,
      350,  350,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  350,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,

      350,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  352,    0,
      350,  350,  350,  350
    } ;

static yyconst flex_int16_t yy_nxt[596] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,    9,    9,    9,
        9,   29,    9,    9,   29,   30,    9,    9,    9,   31,
        4,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,    9,   42,    9,   43,    9,    9,    9,    9,   44,
       45,   46,   47,   48,   49,    9,    9,    9,   50,   51,
       52,   53,   54,   56,   59,   56,   63,   55,   68,  120,
       73,   70,   74,   74,   83,   84,  100,   75,   69,   71,
       72,   64,   76,   86,   87,  101,   88,  124,   77,   78,

       88,   79,   79,  133,   95,   88,   89,   96,   59,   60,
       78,   80,   79,   79,   81,   92,   93,   94,   81,   97,
      105,  108,   80,  106,  121,   81,   98,   66,  109,   81,
       80,   82,   99,  136,  136,  102,   81,  103,  112,  113,
      122,   80,   56,   60,   81,  123,  104,   81,  114,  350,
       56,  115,   56,   74,   74,   81,  256,   65,   82,  257,
      128,  128,  166,  126,  127,   78,  127,   79,   79,  167,
      129,  130,  349,  130,  137,  137,  169,   80,  175,  348,
       81,   81,  126,  127,   81,   81,  170,  171,  127,  129,
      130,  173,  131,  176,  131,  130,   80,  132,  132,  179,

      132,  132,   81,   81,  181,  347,  182,  180,  174,  346,
       81,   81,  138,  122,  139,   56,  345,  184,  123,  184,
       92,   93,  185,  185,  212,  213,  140,  141,  142,  344,
      143,  136,  136,  188,  144,  188,  128,  128,  189,  189,
      343,  145,  146,  147,  148,  149,  186,  187,  191,  187,
      132,  132,  191,  185,  185,  192,  193,  193,  193,  189,
      189,  190,  342,  190,  341,  186,  187,  340,  185,  185,
      191,  187,  194,  269,  137,  137,  240,  240,  191,  127,
      190,  127,  238,  270,  238,  190,  339,  239,  239,  189,
      189,  191,  193,  193,  193,  191,  239,  239,  127,  338,

      130,  337,  130,  127,  241,  241,  241,  336,  194,  240,
      240,  301,  301,  191,  239,  239,  241,  241,  241,  130,
      335,  191,  242,  242,  130,  187,  334,  187,  242,  242,
      301,  301,  333,  332,  242,  242,  331,  330,  329,  328,
      327,  326,  325,  324,  187,  323,  322,  321,  320,  187,
      319,  318,  275,   58,   58,   58,   58,   61,  317,   61,
       65,   65,  316,   65,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  270,  256,  303,  302,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,

      280,  279,  278,  212,  277,  276,  274,  273,  272,  271,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  255,  254,  253,  252,  251,  250,  249,  248,  182,
      180,  247,  173,  170,  166,  246,  245,  244,  243,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,   96,  196,
      195,  183,  178,  177,  172,  168,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,

      151,  150,  135,  134,  125,  350,  119,  118,  117,  116,
      111,  110,  107,   91,   90,   89,   85,   67,   66,   62,
       57,  350,    3,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350

    } ;

static yyconst flex_int16_t yy_chk[596] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    5,    8,    5,   11,    2,   16,   51,
       19,   18,   19,   19,   25,   25,   38,   20,   16,   18,
       18,   11,   20,   27,   27,   38,   29,   65,   20,   22,

       29,   22,   22,  354,   36,   29,   29,   36,   58,    8,
       21,   22,   21,   21,   22,   35,   35,   35,   22,   37,
       40,   42,   21,   40,   51,   21,   37,   65,   42,   21,
       22,   21,   37,   88,   88,   39,   22,   39,   45,   45,
       54,   21,   54,   58,   22,   54,   39,   21,   45,   66,
       56,   45,   56,   74,   74,   21,  218,   66,   21,  218,
       78,   78,  109,   74,   74,   79,   74,   79,   79,  109,
       78,   78,  348,   78,   89,   89,  111,   79,  114,  347,
       79,   81,   74,   74,   79,   81,  111,  111,   74,   78,
       78,  113,   80,  114,   80,   78,   79,   80,   80,  117,

      131,  131,   79,   81,  118,  346,  118,  117,  113,  344,
       79,   81,   91,  122,   91,  122,  339,  126,  122,  126,
      140,  140,  126,  126,  157,  157,   91,   91,   91,  338,
       91,  136,  136,  129,   91,  129,  128,  128,  129,  129,
      337,   91,   91,   91,   91,   91,  128,  128,  133,  128,
      132,  132,  133,  184,  184,  136,  137,  137,  137,  188,
      188,  132,  336,  132,  335,  128,  128,  334,  185,  185,
      133,  128,  137,  232,  137,  137,  192,  192,  133,  185,
      132,  185,  186,  232,  186,  132,  333,  186,  186,  189,
      189,  191,  193,  193,  193,  191,  238,  238,  185,  332,

      189,  331,  189,  185,  194,  194,  194,  330,  193,  240,
      240,  275,  275,  191,  239,  239,  241,  241,  241,  189,
      329,  191,  194,  194,  189,  239,  326,  239,  242,  242,
      301,  301,  323,  321,  241,  241,  320,  317,  316,  315,
      313,  312,  311,  310,  239,  309,  307,  305,  304,  239,
      303,  302,  242,  351,  351,  351,  351,  352,  300,  352,
      353,  353,  299,  353,  298,  297,  292,  290,  289,  288,
      286,  284,  283,  282,  281,  280,  279,  278,  277,  276,
      273,  272,  270,  269,  268,  267,  266,  265,  264,  262,
      261,  260,  259,  257,  256,  255,  254,  253,  252,  251,

      249,  247,  246,  245,  244,  243,  237,  236,  234,  233,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  221,
      219,  215,  214,  213,  212,  209,  208,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  166,  165,  163,  162,  161,
      160,  159,  158,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  139,
      138,  119,  116,  115,  112,  110,  107,  106,  105,  104,
      103,  102,  101,  100,   99,   98,   97,   96,   95,   94,

       93,   92,   87,   83,   73,   60,   49,   48,   47,   46,
       44,   43,   41,   34,   33,   30,   26,   15,   12,   10,
        7,    3,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexc.l"
#line 2 "lexc.l"
static const char lexc_c[] =
"@(#)$Id: lex.yy.c 1.35 $";
/********************************************************************
 *
 *  You may distribute under the terms of either the GNU General Public
 *  License or the Artistic License, as specified in the README file.
 *
 *  For more information about this program, or for information on how
 *  to contact the author, see the README file
 *
 *	ANSI C Lexer
 *
 *	The ANSI C scanner/parser was posted on the net by Jeff Lee,
 *	in 1985. His net address is:
 *		jeff%gatech.CSNet@CSNet-Relay.ARPA, or jeff@gatech.edu
 *	There was no open source license I could find.
 *
 *	Acknowledgement: Jeff Lee and the draft ANSI C standard grammar.
 *	Kernighan and Ritchie "The C Programming Language" 2nd Ed. A13.
 *
 *	This lexer was expanded to support most of the latest extensions
 *	used in gcc.
 *
 *	lexc.l
 *	C lexer for immcc compiler
 *
 *******************************************************************/

#line 41 "lexc.l"
#include	<stdio.h>
#include	<ctype.h>
#include	<string.h>
#include	<assert.h>
#include	<errno.h>
#include	"comp.h"
#include	"gram.tab.h"

static int	yycomment(YYSTYPE* u);
static int	cpp_comment(YYSTYPE* u);
static int	preprocess(YYSTYPE* u);
static int	ignore(YYSTYPE* u);
static void	count(YYSTYPE* u);
static int	check_type(YYSTYPE* u, int qtoken);

#define YY_NO_UNPUT

#ifndef LMAIN
static Symbol	markerSymbol = { "marker", UDF, UDFA, };
static Symbol *	paraList = &markerSymbol;

#define YY_INPUT(buf,result,max_size) \
{\
    int c = '*', n;\
    for ( n = 0; n < max_size && (c = get( yyin, 1 )) != EOF && c != '\n'; ++n )\
	    buf[n] = (char) c;\
    if ( c == '\n' )\
	    buf[n++] = (char) c;\
    if ( c == EOF && ferror( yyin ) )\
	    YY_FATAL_ERROR( "input in flex scanner failed" );\
    result = n;\
}

#define ECHO
#endif

#line 766 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 79 "lexc.l"

#line 953 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 523 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "lexc.l"
{ if (yycomment(&yylval)) yyterminate(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "lexc.l"
{ if (cpp_comment(&yylval)) yyterminate(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "lexc.l"
{ if (preprocess(&yylval)) yyterminate(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "lexc.l"
{ count(&yylval); return AUTO; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "lexc.l"
{ count(&yylval); return BREAK; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "lexc.l"
{ count(&yylval); return CASE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "lexc.l"
{ count(&yylval); return CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "lexc.l"
{ count(&yylval); return CONST; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "lexc.l"
{ count(&yylval); return CONTINUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "lexc.l"
{ count(&yylval); return DEFAULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "lexc.l"
{ count(&yylval); return DO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "lexc.l"
{ count(&yylval); return DOUBLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "lexc.l"
{ count(&yylval); return ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "lexc.l"
{ count(&yylval); return ENUM; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "lexc.l"
{ count(&yylval); return EXTERN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "lexc.l"
{ count(&yylval); return FLOAT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "lexc.l"
{ count(&yylval); return FOR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "lexc.l"
{ count(&yylval); return GOTO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "lexc.l"
{ count(&yylval); return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "lexc.l"
{ count(&yylval); return INT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "lexc.l"
{ count(&yylval); return LONG; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "lexc.l"
{ count(&yylval); return REGISTER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "lexc.l"
{ count(&yylval); return RETURN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "lexc.l"
{ count(&yylval); return SHORT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "lexc.l"
{ count(&yylval); return SIGNED; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "lexc.l"
{ count(&yylval); return SIZEOF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "lexc.l"
{ count(&yylval); return STATIC; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "lexc.l"
{ count(&yylval); return STRUCT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "lexc.l"
{ count(&yylval); return SWITCH; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "lexc.l"
{ count(&yylval); return TYPEDEF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "lexc.l"
{ count(&yylval); return TYPEOF; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "lexc.l"
{ count(&yylval); return UNION; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "lexc.l"
{ count(&yylval); return UNSIGNED; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "lexc.l"
{ count(&yylval); return VOID; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "lexc.l"
{ count(&yylval); return VOLATILE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "lexc.l"
{ count(&yylval); return WHILE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "lexc.l"
{ count(&yylval); return TYPE_NAME;	/* type in GCC 3.2 */ }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 118 "lexc.l"
{ if (ignore(&yylval)) yyterminate(); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 119 "lexc.l"
{ if (ignore(&yylval)) yyterminate(); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 120 "lexc.l"
{ count(&yylval);		/* ignore */ }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 121 "lexc.l"
{ count(&yylval);		/* ignore */ }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 122 "lexc.l"
{ count(&yylval);		/* ignore */ }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 123 "lexc.l"
{ count(&yylval); return CONSTANT;	/* no need to identify octal */ }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 124 "lexc.l"
{ count(&yylval); return STRING_LITERAL; }
	YY_BREAK
/* allow white space because Intel C/C++ v8.1 pre-compiler expands IX0.1 to IX0 .1 */
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 127 "lexc.l"
{ count(&yylval); return check_type(&yylval, 2); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "lexc.l"
{ count(&yylval); return check_type(&yylval, 1); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "lexc.l"
{ count(&yylval); return check_type(&yylval, 0); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 131 "lexc.l"
{ count(&yylval); return CONSTANT;	/* 0xac8 0XAC8UL */ }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 132 "lexc.l"
{ count(&yylval); return CONSTANT;	/* 12 12l 12u 12UL */ }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 133 "lexc.l"
{ count(&yylval); return CONSTANT;	/* '\n' 'A' 'ABC' */ }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 135 "lexc.l"
{ count(&yylval); return CONSTANT;	/* 12e2 12e2f 12E2L */ }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 136 "lexc.l"
{ count(&yylval); return CONSTANT;	/* .1 0.1 1.0 1.0e2 */ }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 137 "lexc.l"
{ count(&yylval); return CONSTANT;	/* 1. 1.e2 */ }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 139 "lexc.l"
{ count(&yylval); return STRING_LITERAL; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 141 "lexc.l"
{ count(&yylval); return RIGHT_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 142 "lexc.l"
{ count(&yylval); return LEFT_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 143 "lexc.l"
{ count(&yylval); return ADD_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 144 "lexc.l"
{ count(&yylval); return SUB_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 145 "lexc.l"
{ count(&yylval); return MUL_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 146 "lexc.l"
{ count(&yylval); return DIV_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 "lexc.l"
{ count(&yylval); return MOD_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 "lexc.l"
{ count(&yylval); return AND_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "lexc.l"
{ count(&yylval); return XOR_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 150 "lexc.l"
{ count(&yylval); return OR_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 151 "lexc.l"
{ count(&yylval); return RIGHT_SH; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 152 "lexc.l"
{ count(&yylval); return LEFT_SH; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 153 "lexc.l"
{ count(&yylval); return INC_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 154 "lexc.l"
{ count(&yylval); return DEC_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 155 "lexc.l"
{ count(&yylval); return PTR_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 156 "lexc.l"
{ count(&yylval); return AND_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 157 "lexc.l"
{ count(&yylval); return OR_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 158 "lexc.l"
{ count(&yylval); return LE_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 159 "lexc.l"
{ count(&yylval); return GE_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 160 "lexc.l"
{ count(&yylval); return EQ_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 161 "lexc.l"
{ count(&yylval); return NE_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 162 "lexc.l"
{ count(&yylval); return ELIPSIS; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 163 "lexc.l"
{ count(&yylval); return ';'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 164 "lexc.l"
{ count(&yylval); return '{'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "lexc.l"
{ count(&yylval); return '}'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "lexc.l"
{ count(&yylval); return ','; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 167 "lexc.l"
{ count(&yylval); return ':'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 168 "lexc.l"
{ count(&yylval); return '='; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 169 "lexc.l"
{ count(&yylval); return '('; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 170 "lexc.l"
{ count(&yylval); return ')'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 171 "lexc.l"
{ count(&yylval); return '['; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 172 "lexc.l"
{ count(&yylval); return ']'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 173 "lexc.l"
{ count(&yylval); return '.'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 174 "lexc.l"
{ count(&yylval); return '&'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 175 "lexc.l"
{ count(&yylval); return '!'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 176 "lexc.l"
{ count(&yylval); return '~'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 177 "lexc.l"
{ count(&yylval); return '-'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 178 "lexc.l"
{ count(&yylval); return '+'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 179 "lexc.l"
{ count(&yylval); return '*'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 180 "lexc.l"
{ count(&yylval); return '/'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 181 "lexc.l"
{ count(&yylval); return '%'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 182 "lexc.l"
{ count(&yylval); return '<'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 183 "lexc.l"
{ count(&yylval); return '>'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 184 "lexc.l"
{ count(&yylval); return '^'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 185 "lexc.l"
{ count(&yylval); return '|'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 186 "lexc.l"
{ count(&yylval); return '?'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 188 "lexc.l"
{ count(&yylval); }
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 189 "lexc.l"
{ count(&yylval);	/* individual token */ }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 190 "lexc.l"
{ count(&yylval); 	/* ignore bad characters */ }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 192 "lexc.l"
ECHO;
	YY_BREAK
#line 1562 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 350);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 192 "lexc.l"



int		gramOffset = 0;		/* count input in lex */

static int	gramLine   = 1;
int		column = 0;
FILE*		saveFP = NULL;

int
yywrap(void)
{
    return 1;
}

/********************************************************************
 *
 *	C comment
 *
 *******************************************************************/

static int
yycomment(YYSTYPE* u)
{
    int c;

    count(u);				/* count C comment start */

    if ((c = input()) == EOF) return 1;

    do {				/* start C style comment */
	while (c != '*') {
	    gramOffset++;
#if YYDEBUG && defined LMAIN
	    if (iC_debug & 040) putc(c, yyout);
#endif
	    if (c == '\n') {
		column = 0;
		gramLine++;
	    } else if (c == '\t') {
		column += 8 - (column % 8);
	    } else {
		column++;
	    }
	    if ((c = input()) == EOF) return 1;
	}
	column++;			/* count '*' */
	gramOffset++;
#if YYDEBUG && defined LMAIN
	if (iC_debug & 040) putc(c, yyout);
#endif
    } while ((c = input()) != '/');

    if (c == EOF) return 1;
    column++;				/* count '/' */
    gramOffset++;
#if YYDEBUG && defined LMAIN
    if (iC_debug & 040) putc(c, yyout);
#endif

    return 0;
} /* yycomment */

/********************************************************************
 *
 *	C++ comment
 *
 *	no need to process '\t'
 *
 *******************************************************************/

static int
cpp_comment(YYSTYPE* u)
{
    int c;
#ifndef LMAIN
    static int errorCnt = 0;
#endif

    count(u);				/* count "//" */

    do {				/* start C++ style comment */
	if ((c = input()) == EOF) return 1;    /* error EOF in comment */
	gramOffset++;
#if YYDEBUG && defined LMAIN
	if (iC_debug & 040) putc(c, yyout);
#endif
    } while (c != '\n');
#ifndef LMAIN
    if (iC_Pflag && errorCnt++ == 0) {	/* report only once */
	warning("C++ style comments are not allowed in ISO C90:", yytext);
    }
#endif
    column = 0;
    gramLine++;
    return 0;
} /* cpp_comment */

/********************************************************************
 *
 *	Pre-processor line - more lines if last character is '\'
 *
 *	no need to process '\t'
 *
 *******************************************************************/

static int
preprocess(YYSTYPE* u)
{
    int c = 0;
    int prev;

    count(u);				/* count "#" */

    do {				/* pre processeor line */
	do {
	    prev = c;
	    if ((c = input()) == EOF) return 1;    /* error EOF in line */
	    gramOffset++;
#if YYDEBUG && defined LMAIN
	    if (iC_debug & 040) putc(c, yyout);
#endif
	} while (c != '\n');
	column = 0;
	gramLine++;
    } while (prev == '\\');
    return 0;
} /* preprocess */

/********************************************************************
 *
 *	__attribute__ ((__mode__ (__HI__)))
 *	__asm__ __volatile__ ("btsl %1,%0" : "cc","memory")
 *
 *******************************************************************/

static int
ignore(YYSTYPE* u)
{
    int c;
    int  bracketCount = 0;

    count(u);				/* count "__atribute__" */

    for (;;) {
	if ((c = input()) == EOF) return 1;    /* error EOF in comment */
	gramOffset++;
#if YYDEBUG && defined LMAIN
	if (iC_debug & 040) putc(c, yyout);
#endif
	if (c == '\n') {
	    column = 0;
	    gramLine++;
	} else if (c == '\t') {
	    column += 8 - (column % 8);
	} else {
	    column++;
	    if (c == '(') {
		bracketCount++;
	    } else if (c == ')' && --bracketCount <= 0) {
		break;
	    }
	}
    }
    return 0;
} /* ignore */

/********************************************************************
 *
 *	Count collumns, lines and bytes in gramOffset
 *
 *	When include files are processed (lexflag & C_NO_COUNT)
 *	it is important that "\n" are individual tokens not grouped
 *	as white space. Otherwise the trailing whitespace from an
 *	include file is grouped in yytext[] with the leading whitespace
 *	after the #include line and counted after C_NO_COUNT is reset.
 *
 *******************************************************************/

static void
count(YYSTYPE* u)
{
    int i;

    u->tok.start = gramOffset;

    for (i = 0; yytext[i] != '\0'; i++) {
	if (yytext[i] == '\n') {
	    column = 0;
	    gramLine++;
	} else if (yytext[i] == '\t') {
	    column += 8 - (column % 8);
	} else {
	    column++;
	}
	gramOffset++;
    }

    u->tok.end = gramOffset;

#if YYDEBUG && defined LMAIN
    if (iC_debug & 040) { ECHO; }
#endif
} /* count */

/********************************************************************
 *
 *	Check type of an input token word
 *
 *	If token is a CTYPE return TYPE_NAME
 *	Else if token is an immediate variable of ftype UDFA and type
 *		ARNC or LOGC return IMM_ARRAY_IDENTIFIER with pointer
 *		to Symbol in tok
 *	Else if token is an immediate variable of ftype ARITH or GATE
 *		return IMM_IDENTIFIER with pointer to Symbol in tok
 *		for any other imm variable return YYERRCODE
 *	Else token is a CWORD
 *		create a new Symbol and return CWORD
 *		when this Symbol is recognised as a CTYPE it is
 *			placed in the symbol table
 *		otherwise it is deleted
 *
 *******************************************************************/

static int
check_type(YYSTYPE* u, int qtoken)
{
    Symbol *	sp = 0;
    int		n;
    char	iqt[2];			/* char buffers - space for 0 terminator */
    char	xbwl[2];
    int		byte;
    int		bit;
    int		ixd;
#ifdef LMAIN
#define buffer	yytext
    ixd = -1;				/* limit for I/O index (-1 no limit) */

#else
    int		c;
    int		i;
    char	buffer[BUFS];		/* buffer for modified names */
    char	tail[8];		/* compiler generated suffix _123456 max */

    ixd = iC_maxIO;			/* limit for I/O index (-1 no limit) */
    if (yytext[0] == '$') {
	/********************************************************************
	 *  Identifier starts with a '$'. gcc can handle this if the next character
	 *  is alpha but not if it is a digit.
	 *  Most assemblers have problems with leading '$' - hence the warning.
	 *******************************************************************/
	if (isdigit(yytext[1])) {
	    ierror("asm error due to '$' followed by digit starting identifier:", yytext);
	} else {
	    warning("possible asm error due to '$' character starting identifier:", yytext);
	}
    }
    if (qtoken == 2) {
	iC_toIEC1131(yytext, buffer, BUFS, iqt, xbwl, &byte, &bit, tail);
	/********************************************************************
	 *  the Intel C/C++ v8.1 pre-compiler expands IX0.1 to IX0 .1
	 *  Generally if yacc were to handle the '.' as a seperate token,
	 *  white space would be allowed as it would in C for the operator '.'
	 *  If we allow white space here we will have the same effect without
	 *  changing the grammar.
	 *******************************************************************/
	for (i = n = 0; n <= yyleng; n++) {
	    c = buffer[n];
	    if (! isspace(c)) {		/* space \f \n \r \t \v */
		if (i < n) {
		    buffer[i] = c;
		}
		i++;
	    }
	}
    } else {
	strncpy(buffer, yytext, BUFS);
    }
    if (iFunSymExt && !qtoken) {
	if (iRetSymbol.v && strcmp(yytext, "this") == 0) {
	    sp = iRetSymbol.v;		/* function return Symbol */
	} else {
	    strncpy(iFunSymExt, yytext, iFunEnd - iFunSymExt);
	    sp = lookup(iFunBuffer);	/* maybe function internal Symbol */
	    *iFunSymExt = '\0';
	}
    }
#endif
    if (
#ifndef LMAIN
	sp == 0 &&
#endif
	(sp = lookup(buffer)) == 0) {
	/********************************************************************
	 *  Recognise and install undefined IEC1131 I/O variables. Otherwise
	 *  they have to be declared as imm variables, which is not consistent
	 *  with the iC use of I/O variables, which need not be declared.
	 *  Mark QXx.y QBz etc by setting em |= EO (also done in iClex())
	 *******************************************************************/
	if ((n = sscanf(buffer, "%1[IQT]%1[XBWL]%d.%d", iqt, xbwl, &byte, &bit)) >= 3) {
	    unsigned char	wplus = 0;
	    unsigned char	typ = UDF;
	    unsigned char	ftyp = UDFA;

	    if (xbwl[0] != 'X') {
		wplus = GATE - ARITH;	/* QB, QW, QL or IB, IW, IL */
		assert(wplus == INPX - INPW);
		goto foundQIT;
	    }
	    if (n == 4) {		/* QX, IX or TX */
		if (bit < 8) {
		    foundQIT:
		    ftyp = GATE - wplus;	/* GATE or ARITH */
		    if (iqt[0] != 'Q') {
			typ = INPX - wplus;	/* INPX or INPW */
			if (iqt[0] == 'T') {
			    ixd = xbwl[0] == 'X' ? 1 : 0;	/* TX0.7 is max */
			}
		    }
		    if (ixd < 0 || byte < ixd) {
			sp = install(buffer, typ, ftyp);
			if (iqt[0] == 'Q') {
			    sp->em |= EO;	/* marks variable as Q... */
			}
			goto foundSymbol;
		    } else {
			char errorMsg[41];	/* length of message + 5 digit number + \0 */
			snprintf(errorMsg, 40, "I/O byte address must be less than %d", ixd);
			YY_FATAL_ERROR( errorMsg );\
		    }
		} else {
		    YY_FATAL_ERROR( "I/O bit address must be less than 8" );\
		}
	    }
	}
    } else {
	foundSymbol:
	if (sp->type < MAX_LS && (sp->fm & FM) == 0) {	/* only imm types */
#ifndef LMAIN
	    if (lexflag & C_NO_COUNT) goto inInclude;	/* ignore imm in C includes */
	    if ((lexflag & C_BLOCK1) == 0) {
		if ((lexflag & C_PARA) == C_PARA) {
		    markParaList(sp);	/* mark Symbol as parameter on glist */
		}
		if (
#if YYDEBUG && ! defined(SYUNION)
		    sp->v_glist
#else
		    sp->v_cnt > 2	/* v_cnt instead of v_glist for SYUNION */
#endif
		) {
		    u->tok.symbol = sp;
		    return IDENTIFIER;	/* name of imm variable temporarily C parameter */
		}
	    }
#endif
	    while (sp->type == ALIAS) {
		sp = sp->list->le_sym;	/* with token of original */
	    }
	    u->tok.symbol = sp;
	    if (sp->ftype == ARITH || sp->ftype == GATE) {
		return IMM_IDENTIFIER;	/* analyze type errors in parser */
	    } else if (sp->ftype == UDFA && (sp->type == ARNC || sp->type == LOGC)) {
		return IMM_ARRAY_IDENTIFIER;	/* immC array */
	    } else {
		return YYERRCODE;	/* other imm node is an error */
	    }
#ifndef LMAIN
	} else if (sp->type == KEYW) {
	    goto inInclude;		/* KEYWs only required in iC compile */
#endif
	} else if (sp->type == CTYPE) {
	    u->tok.symbol = sp;
	    return TYPE_NAME;
	} else if (sp->type == CWORD) {
	    u->tok.symbol = sp;
	    return IDENTIFIER;		/* CNAME C function recognized in comp.y */
	}
	return YYERRCODE;		/* internal imm node is an error */
    }
#ifndef LMAIN
  inInclude:
#endif
    sp = (Symbol *) iC_emalloc(sizeof(Symbol));
    sp->name = iC_emalloc(yyleng + 1);	/* +1 for '\0' */
    strcpy(sp->name, yytext);
    sp->type = CWORD;
    sp->ftype = UDFA;
    u->tok.symbol = sp;			/* sp->next === NULL */
#if YYDEBUG && defined LMAIN
    if ((iC_debug & 0402) == 0402) fprintf(iC_outFP, "\nC %-15s %d %d\n", sp->name, sp->type, sp->ftype);
#endif
    return IDENTIFIER;
} /* check_type */

/********************************************************************
 *
 *	Delete unnecessary Symbol
 *
 *******************************************************************/

void
delete_sym(Token* tokp)
{
    Symbol *	sp;
    Symbol *	tsp;

    if ((sp = tokp->symbol) != NULL && sp->type > MAX_LS) {
	tokp->symbol = NULL;
#if YYDEBUG && defined LMAIN
	if ((iC_debug & 0402) == 0402) fprintf(iC_outFP, "\nD %-15s %d %d %u\n", sp->name, sp->type, sp->ftype, sp->u_val);
#endif
	if ((tsp = lookup(sp->name)) != NULL &&	/* check if in symbol table */
	    tsp == sp) {			/* and not generated by C parse */
	    unlink_sym(sp);			/* unlink Symbol from symbol table */
	}
	if (sp->name) {
	    free(sp->name);			/* completely delete name (no longer cleared in unlink_sym - jw 20141007) */
	}
	free(sp);				/* and Symbol */
    }
} /* delete_sym */
#ifndef LMAIN

/********************************************************************
 *
 *	Mark an imm Symbol as a parameter or function internal C variable
 *	on glist. The immediate Symbol is hidden till the end of the
 *	current C-function, when clearParaList() will clear the list.
 *	The same Symbol may appear several times - check for duplicates.
 *
 *	Alternatively mark an imm Symbol as a global C variable, which
 *	will be hidden in all subsequent literal blocks and C functions.
 *
 *******************************************************************/

void
markParaList(Symbol * sp)
{
    assert(sp && sp->type < IFUNCT);		/* allows IFUNCT to use union v.cnt */
    if (
#if YYDEBUG && ! defined(SYUNION)
	sp->v_glist == 0
#else
	sp->v_cnt <= 2				/* v_cnt instead of v_glist for SYUNION */
#endif
    ) {
	if ((lexflag & C_FUNCTION) == 0) {
	    sp->v_glist = &markerSymbol;	/* mark C globally */
	} else {
	    sp->v_glist = paraList;		/* mark on paraList */
	    paraList = sp;
	}
    }
} /* markParaList */

/********************************************************************
 *
 *	Clear parameter list from C function internal entries
 *
 *******************************************************************/

void
clearParaList(int flag)
{
    Symbol * sp;

    while (paraList != &markerSymbol) {
	sp = paraList->v_glist;
	assert(sp && sp->type < IFUNCT);	/* allows IFUNCT to use union v.cnt */
	paraList->v_glist = 0;
	paraList = sp;
    }
    if (flag) {
	lexflag |= (C_PARA|C_FUNCTION);
    } else {
	lexflag &= ~(C_PARA|C_FUNCTION);
    }
} /* clearParaList */
#endif

