#!/bin/bash
# make all iC components for debugging and install them
makeAll -qgcrtlm
make install
# optionally make selected iC applications with the new libict.a
# may use all options of iCmake with 'm'
iCmake $*
# $Id: m,v 1.4 2005/01/17 19:23:18 jw Exp $
