#!/usr/bin/ksh -p

########################################################################
#
#	make ict with OPT=TCP
#
#	$Id: makeIct,v 1.3 2001/02/21 16:20:29 jw Exp $
#
########################################################################

if [[ -f Make_tmp ]]; then
    echo 'Error makeIct: Make_tmp exists as file ??? - nothing made' >&2
    exit 1;
fi
test -d Make_tmp || mkdir Make_tmp;
mv main.o Make_tmp
if [[ -d PptcObjs ]]; then
    mv PptcObjs/* .
else
    mkdir PptcObjs
fi
make OPT='-DTCP' ict
mv main.o ict.o PptcObjs
mv Make_tmp/* .
rmdir Make_tmp
