#!/usr/bin/ksh -p

########################################################################
#
#	make an executable file from an iC file
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/} [-lh] [-v<N>] 'file ...' >&2
    echo '	-l	link all the iC files into one application' >&2
    echo '	-v<N>	use pplc<N> eg pplc1 pplc2 ...' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: makex,v 1.4 2000/11/23 16:48:46 jw Exp $' >&2
}

link=0
flag=noerror
a=""
v=""

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    l*)	link=1;;
	    v*)	option=${option#?};
		if [[ -n $option ]]; then
		    v=$option;
		else
		    shift; v=$1;
		fi
		break;;
	    h*)	usage; exit 255;;
	    *) aflag="-$option"; break;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

for f in $*; do
    file=$f
    base=${file%.*}
    if [[ -z $first ]]; then
	first=$base
    fi
    if [[ $file = $base ]]; then
	file="$base.p"
    fi
    if [[ ! -f $file ]]; then
	echo "iC file $file does not exist" >&2
	usage
	exit 1;
    fi
    echo $file
    if [[ $link != 1 ]]; then
	if pplc$v -d74 -o $base.c -l $base.lst $file; then
	    gcc -g -DYYDEBUG -o $base $base.c list.c load.a
	fi
    else
	if [[ $first != $base ]]; then
	    a="-a"
	fi
	if pplc$v $a -d74 -o $base.c -l $base.lst $file; then
	    list="$list $base.c"
	else
	    list="$list ERROR:$base.c"
	    flag=error
	fi
    fi
done

if [[ $link = 1 ]]; then
    if [[ $flag = noerror ]]; then
	echo "link $first from$list"
	gcc -g -DYYDEBUG -o $first $list list.c load.a
    else
	echo "pplc$v compile errors in $list" >&2
    fi
fi
