#!/bin/bash

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john@je-wulff.de>
#
#	make icc ict libict.a
#
#	use egrep rather than grep -E so it works on older Unix systems
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-qh] [path]' >&2
    echo '	call make for icc, ict and libict.a with the correct options' >&2
    echo '	path is optionally supplied by Makefile for executing scripts' >&2
    echo '	in the correct path (default ./)' >&2
    echo '	-q	output only headings and error messages' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: makeAll,v 1.8 2001/03/17 00:20:17 jw Exp $' >&2
}

q=""
path="./"

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n $option ]]; do
	    case $option in
	    q*)	q=1;;	# echo only - dont kill
	    h*)	usage; exit 255;;
	    *)	x=${option#?}; option=${option%$x}
	    	echo "$name: unexpected option $option in $1" >&2
		usage; exit 254;;
	    esac
	    option=${option#?}
	done
	;;
    *)	break;;
    esac
    shift
done

if [[ $# > 0 ]]; then
    path=$1
fi

if test -f cexe.c_empty && ! cmp -s cexe.c cexe.c_empty; then
    rm -f cexe.o
    cp -p cexe.c_empty cexe.c
fi
echo "make icc"
make icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
echo "make ict"
${path}makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
echo "make libict.a"
${path}makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
true
