#!/usr/bin/ksh -p

########################################################################
#
#	make the load.a lib with OPT=LOAD
#
#	$Id: makeload,v 1.3 2000/06/04 10:08:14 jw Exp $
#
########################################################################

#define TCP

if [[ -e Make_tmp ]]; then echo 'Make_tmp exists ??? - nothing made'; exit 1; fi
mkdir Make_tmp
mv pptc.o link.o rsff.o scan.o Make_tmp
if [[ -d LoadObjs ]]; then
    mv LoadObjs/* .
else
    mkdir LoadObjs
fi
export OPT="-DLOAD $TCP"
make load.a
export OPT=$TCP
mv pptc.o link.o rsff.o scan.o LoadObjs
mv Make_tmp/* .
rmdir Make_tmp
