#!/bin/sh

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john.wulff@inka.de>
#
#	make the libict.a library with OPT=LOAD
#
#	$Id: makeLib,v 1.10 2001/03/18 14:03:15 jw Exp $
#
########################################################################

if [ -f Make_tmp ]; then
    echo 'Error makeload: Make_tmp exists as file ??? - nothing made' >&2
    exit 1;
fi
test -d Make_tmp || mkdir Make_tmp;
mv link.o rsff.o scan.o Make_tmp
if [ -d LoadObjs ]; then
    mv LoadObjs/* .
else
    mkdir LoadObjs
fi
make OPT='-DLOAD -DTCP' libict.a
mv ict.o link.o rsff.o scan.o LoadObjs
mv Make_tmp/* .
rmdir Make_tmp
