#!/bin/sh

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john.wulff@inka.de>
#
#	make ict with OPT=TCP
#
#	$Id: makeIct,v 1.5 2001/03/16 16:51:34 jw Exp $
#
########################################################################

if [[ -f Make_tmp ]]; then
    echo 'Error makeIct: Make_tmp exists as file ??? - nothing made' >&2
    exit 1;
fi
test -d Make_tmp || mkdir Make_tmp;
mv main.o Make_tmp
if [[ -d PptcObjs ]]; then
    mv PptcObjs/* .
else
    mkdir PptcObjs
fi
make OPT='-DTCP' ict
mv main.o ict.o PptcObjs
mv Make_tmp/* .
rmdir Make_tmp
