#!/bin/bash

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john@je-wulff.de>
#
#	make icc ict libict.a lmain
#
#	use egrep rather than grep -E so it works on older Unix systems
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-qh]' >&2
    echo '	call make for icc, ict and libict.a with the correct options' >&2
    echo '	-q	output only headings and error messages' >&2
    echo '	-c	make icc with YYDEBUG -t trace output possible' >&2
    echo '	-t	make ict with YYDEBUG -t trace output possible' >&2
    echo '	-l	make libict.a with YYDEBUG -t trace output possible' >&2
    echo '	-m	make lmain with YYDEBUG' >&2
    echo '		see usage of icc, ict and applications for other options' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: makeAll,v 1.11 2002/09/03 17:30:13 jw Exp $' >&2
}

makeIct ()
{
    mv main.o comp.o genr.o gram.o lexc.o link.o rsff.o scan.o Make_tmp
    if [ -d PptcObjs ]; then
	mv PptcObjs/* .
    else
	mkdir PptcObjs
    fi
    make OPT="-DTCP$t" ict
    mv main.o ict.o comp.o genr.o gram.o lexc.o link.o rsff.o scan.o PptcObjs
    mv Make_tmp/* .
}

makeLib ()
{
    mv scid.o link.o rsff.o scan.o Make_tmp
    if [ -d LoadObjs ]; then
	mv LoadObjs/* .
    else
	mkdir LoadObjs
    fi
    make OPT="-DLOAD -DTCP$l" libict.a
    mv ict.o scid.o link.o rsff.o scan.o LoadObjs
    mv Make_tmp/* .
}

makeLmain ()
{
    mv gram.o lexc.o Make_tmp
    if [ -d LmainObjs ]; then
	mv LmainObjs/* .
    else
	mkdir LmainObjs
    fi
    make OPT="-DLMAIN$m" lmain
    mv gram.o lexc.o LmainObjs
    mv Make_tmp/* .
}

q=""
c=""
t=""
l=""
m=""

while [ $# -gt 0 ]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [ -n "$option" ]; do
	    case $option in
	    q*)	q=1;;	# echo only - dont kill
	    c*)	c="-DYYDEBUG";;
	    t*)	t=" -DYYDEBUG";;
	    l*)	l=" -DYYDEBUG";;
	    m*)	m=" -DYYDEBUG";;
	    h*)	usage; exit 255;;
	    *)	x=${option#?}; option=${option%$x}
	    	echo "$name: unexpected option $option in $1" >&2
		usage; exit 254;;
	    esac
	    option=${option#?}
	done
	;;
    *)	break;;
    esac
    shift
done

if [ -f Make_tmp ]; then
    echo 'Error makeAll: Make_tmp exists as file ??? - nothing made' >&2
    exit 1;
fi
test -d Make_tmp || mkdir Make_tmp;

if test -f cexe.c_empty && ! cmp -s cexe.c cexe.c_empty; then
    rm -f cexe.o
    cp -p cexe.c_empty cexe.c
fi

echo "make OPT=$c icc"
make OPT=$c icc 2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
echo "make OPT=-DTCP$t ict"
makeIct  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
echo "make OPT=-DLOAD -DTCP$l libict.a"
makeLib  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi
echo "make OPT=-DLMAIN$m lmain"
makeLmain  2>&1 | if [ -n "$q" ]; then egrep -i "(error|warning|up to date|:[A-Z_a-z. 0-9]+:)"; else cat; fi

rmdir Make_tmp
true
