#!/usr/bin/ksh -p

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john@je-wulff.de>
#
#	make icc ict libict.a
#
#	$Id: makeall,v 1.6 2001/03/07 12:30:06 jw Exp $
#
########################################################################

if test -f cexe.c_empty && ! cmp -s cexe.c cexe.c_empty; then
    rm -f cexe.o
    cp -p cexe.c_empty cexe.c
fi
echo "make icc"
make icc 2>&1 | if [ "$1" != '-e' ]; then grep -iE "(error|warning|up to date|:[0-9]+:)"; else cat; fi
echo "make ict"
makeIct  2>&1 | if [ "$1" != '-e' ]; then grep -iE "(error|warning|up to date|:[0-9]+:)"; else cat; fi
echo "make libict.a"
makeload 2>&1 | if [ "$1" != '-e' ]; then grep -iE "(error|warning|up to date|:[0-9]+:)"; else cat; fi
true
