#!/usr/bin/ksh -p

########################################################################
#
#	make icc icl ict ict.a
#
#	$Id: makeall,v 1.4 2001/02/21 16:20:29 jw Exp $
#
########################################################################

if ! cmp -s cexe.c cexe.c_empty; then
    cp -p cexe.c_empty cexe.c
fi
echo "make icc"
make icc 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
#echo "make icl"
# make icl 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
echo "make ict"
makeIct 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
echo "make ict.a"
makeload 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
