#!/usr/bin/ksh -p

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john@je-wulff.de>
#
#	make icc icl ict libict.a
#
#	$Id: makeall,v 1.5 2001/03/02 12:56:32 jw Exp $
#
########################################################################

if ! cmp -s cexe.c cexe.c_empty; then
    cp -p cexe.c_empty cexe.c
fi
echo "make icc"
make icc 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
#echo "make icl"
# make icl 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
echo "make ict"
makeIct 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
echo "make libict.a"
makeload 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
