#!/usr/bin/ksh -p

########################################################################
#
#	make the load.a lib with OPT=LOAD
#
#	$Id: makeload,v 1.6 2001/01/13 19:27:58 jw Exp $
#
########################################################################

if [[ -f Make_tmp ]]; then
    echo 'Error makeload: Make_tmp exists as file ??? - nothing made' >&2
    exit 1;
fi
test -d Make_tmp || mkdir Make_tmp;
mv link.o rsff.o scan.o Make_tmp
if [[ -d LoadObjs ]]; then
    mv LoadObjs/* .
else
    mkdir LoadObjs
fi
make OPT='-DLOAD -DTCP' load.a
mv pptc.o link.o rsff.o scan.o LoadObjs
mv Make_tmp/* .
rmdir Make_tmp
