#!/bin/sh

########################################################################
#
#	Copyright (C) 2000-2001  John E. Wulff
#
#   You may distribute under the terms of either the GNU General Public
#   License or the Artistic License, as specified in the README file.
#
#   For more information about this program, or for information on how
#   to contact the author, see the README file or <john@je-wulff.de>
#
#	perlinstall
#
#	install Msg.pm in @INC path	must be super user
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-uh] file ...' >&2
    echo '		install (cp) the files to the @INC path' >&2
    echo '	-u	uninstall (rm) the files from the @INC path' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: perlinstall,v 1.4 2001/03/16 16:51:34 jw Exp $' >&2
}

u=''

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    u*)	u=uninstall;;
	    h*)	usage; exit 255;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

for d in /usr/lib/perl5/site_perl/5*; do
    if [[ -d $d && -d $d/i586-linux ]]; then
	perlPath=$d/i586-linux;	# find the highest version
    fi
done

if [[ -n $perlPath ]]; then
    if [[ -z $u ]]; then
	for f in $*; do
	    cp -f $f $perlPath
	    echo "copied Msg.pm ==> $perlPath"
	done
    else
	for f in $*; do
	    rm -f $perlPath/$f
	    echo "deleted $perlPath/$f"
	done
    fi
else
    echo 'NO /usr/lib/perl5/site_perl/5*/i586-linux - installation failed'
    exit 1
fi
