#!/bin/sh

########################################################################
#
#	sortm28.sh
#
#	This demo starts iCserver and the control program 'sortm28' which
#	is generated by iCmake sortm28.ic.  It also starts an iCbox with
#	8 digital inputs IX0.0 - IX0.7, which in this case are push-buttons
#	with a 250 ms turn-off delay. They only need to be clicked to send
#	a 250 ms on/off pulse to the application.  It also implements
#	8 digital outputs QX0.0 - QX0.7.
#
#	Each input starts a timer varying from 12 ticks for IX0.0 to 92 ticks
#	for IX0.7. At the end of their respective timer delays the outputs
#	QX0.0 to QX0.7 will turn on for 10 ticks.
#
#	Stop the demo by left mouse clicking (X) in generated iCbox
#
########################################################################

echo '$ iCserver -kr -R sortm28 -l  -R iCbox -nsortm28-IO IX0,,250 QX0'
iCserver -kr -R sortm28 -l  -R iCbox -nsortm28-IO IX0,,250 QX0
