#!/bin/bash

usage()
{
    echo "Make iC components immcc and libict.a for debugging and install them" >&2
    echo "Usage $name[ -iudsyeh][ -D<OPT>][ -W<OPT>][[ <iCmake_options>] <iC_sources>]" >&2
    echo 'Usage:	'${0##*/}' [-qgcrtlmdeCRTLMszh] [-D<OPT>] [-o<OBJ>]' >&2
    echo "	-i	execute chmod +s /usr/bin/install /usr/bin/ranlib as su once" >&2
    echo "		this is required to run make install as an ordinary user" >&2
    echo '	-r	additionally make standalone compiler icr' >&2
    echo '	-t	additionally make standalone compiler ict' >&2
    echo '	-m	additionally make standalone compiler lmain' >&2
    echo '	-u	make any compiler targets with Symbol SYUNION option' >&2
    echo '	-D<OPT>	make all targets with <OPT> defined' >&2
    echo '	-W<OPT>	compile all C sources with -W<OPT> (useful for -Wall)' >&2
    echo '	-e	make all targets with EFENCE option and link with -lefence' >&2
    echo '	-d	make with -DDEQ Gate option (make clean required first)' >&2
    echo '		double ended queue processing is slightly faster' >&2
    echo '	-s	make with -DINT_MAX=32767 (make clean required first)' >&2
    echo '		(on a 16 bit system INT_MAX is 32767 and -s is not required)' >&2
    echo '		simulates compilation for a 16 bit system, which does' >&2
    echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
    echo '	-y	make with -DLONG16        (make clean required first)' >&2
    echo '		produces code for long int arithmetic on a 16 bit system' >&2
    echo '	-z	echo compiler calls with all options for debugging' >&2
    echo '	-h	this help text' >&2
    echo "	<iC_sources>  list of iC source files which will be made with iCmake" >&2
    echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
    echo '$Id: m,v 1.10 2008/02/24 22:59:01 jw Exp $Id: m,v 1.10 2008/02/24 22:59:01 jw Exp $' >&2
}

name=${0##*/}
rtmudsye=''
dw=''
z=0

while getopts ":irtmudsyeD:W:zh" opt; do
    case $opt in
    i )
	echo "Enter root:" >&2
	sudo chmod +s /usr/bin/install /usr/bin/ranlib
	echo "chmod +s /usr/bin/install /usr/bin/ranlib" >&2
	echo "Exit  root:" >&2
	sudo -k
	exit
	;;
    r ) rtmudsye="${rtmudsye}r";;
    t ) rtmudsye="${rtmudsye}t";;
    m ) rtmudsye="${rtmudsye}m";;
    u ) rtmudsye="${rtmudsye}u";;
    d ) rtmudsye="${rtmudsye}d";;
    s ) rtmudsye="${rtmudsye}s";;
    y ) rtmudsye="${rtmudsye}y";;
    e ) rtmudsye="${rtmudsye}e";;
    D ) dw="$dw -D$OPTARG";;
    W ) dw="$dw -W$OPTARG";;
    z )	z=1;rtmudsye="${rtmudsye}z";;
    h )	usage; exit 127;;
    \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
    esac
done
shift $(($OPTIND - 1))

echo "### makeAll -qgcl$rtmudsye$dw"
./makeAll -qgcl$rtmudsye$dw
echo "### make install"
make install
if [ $# -gt 0 ]; then
    # optionally make selected iC applications with the new libict.a
    # may use all options of iCmake with 'm'
    echo "### iCmake $*"
    iCmake $*
fi
