#!/bin/bash

########################################################################
#
#	make icc$v.v of immcc$v ict$v and libict$v.a
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-dh] [ver ...]' >&2
    echo '	-d	diff previously made files' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: mkpp,v 1.6 2005/07/04 13:41:25 jw Exp $' >&2
}

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    d*)	d=diff;;
	    h*)	usage; exit 255;;
	    *) aflag="-$option"; break;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

if [[ $# != 0 ]]; then
    versions=$*
else
    versions=$(echo Alex??)
fi

for w in $versions; do
    if [[ ! -L $w ]]; then
	v=${w##*[a-z]}
	echo "### $v ###"
	if [[ ! -f immcc$v ]]; then
	    echo "Error: immcc$v does not exist" >&2
	elif [[ ! -f ict$v ]]; then
	    echo "Error: ict$v does not exist" >&2
	elif [[ ! -f libict$v.a ]]; then
	    echo "Error: libict$v.a does not exist" >&2
	else
	    if [[ -n "$d" ]]; then
		mkv immcc$v ict$v libict$v.a | diff - icc$v.v
	    else
		mkv immcc$v ict$v libict$v.a > icc$v.v
	    fi
	fi
    fi
done
