#!/bin/bash
########################################################################
#
#	make iC test cases from pm.lt which may specify linking iC's
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-ASRxzNh] [-v<N>] [-y<opt>]' >&2
    echo '	-v<N>	use ict<N> eg ict1 ict2 ... with libict1.a libict2.a ...' >&2
    echo '	-y<opt>	call immcc with extra -d<opt> orred into normal -d474' >&2
    echo '	-A	compile output ARITHMETIC ALIAS nodes for symbol debugging' >&2
    echo '	-S	strict compile - all immediate variables must be declared' >&2
    echo '	-R      no maximum error count (default: abort after 100 errors)' >&2
    echo '	-i	produce file.ini with load info but no INITIALIZATION' >&2
    echo '	-I	produce file.ini with load info and full INITIALIZATION' >&2
    echo '	-J	produce file.ini without load info but full INITIALIZATION' >&2
    echo '	-x	auxiliary files .iC_list1.h .iC_list2.h not deleted' >&2
    echo '	-z	echo compiler calls with all options for debugging' >&2
    echo '	-N	No nice with calls of immcc and gcc compilers (default is nice)' >&2
    echo '	-h	this help text' >&2
    echo '	uses iCmake -v<N> -y<opt> to make each line of the list pm.lt' >&2
    echo '	which has mostly individual lines naming one source eg. xxx.ic' >&2
    echo '	but may also have lines like "-l a.ic a1.ic a2.ic" for linking' >&2
    echo 'Author:	John E. Wulff        <john@je-wulff.de>' >&2
    echo '$Id: mm,v 1.13 2005/07/31 17:59:43 jw Exp $' >&2
}

v=""
z=0
I=""

while [[ $# -gt 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    v*)	option=${option#?}
		if [ -n "$option" ]; then
		    v="$v -v$option"
		else
		    echo "-v must specify an option";
		    usage; exit 254;
		fi
		break;;
	    y*)	option=${option#?}
		if [ -n "$option" ]; then
		    v="$v -y$option"
		else
		    echo "-y must specify an option";
		    usage; exit 254;
		fi
		break;;
	    x*)	v="$v -x";;
	    A*)	v="$v -A";;
	    S*)	v="$v -S";;
	    R*)	v="$v -R";;
	    N*)	v="$v -N";;
	    i*) I=" -i";;
	    I*) I=" -I";;
	    J*) I=" -J";;
	    z*)	z=1;v="$v -z";;
	    h*)	usage; exit 255;;
	    *)	echo "unknown flag -$option";
		usage; exit 255;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

while true; do
    read line
    if [[ -z "$line" ]]; then
	break
    fi
    if [ $z -eq 1 ]; then
	echo "iCmake$I$v $line" >&2
    fi
    iCmake$I$v $line
done < pm.lt 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\.o\((\.[a-z][a-z]*+0x[0-9a-f]*)\)*:/ s//\/tmp\/x.o:/' > Init.out
rm -rf ic[0-9].*
