#!/bin/bash

########################################################################
#
#	make a function version of icr or ict
#
#	make a new icr or ict only if the iC file has functions
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-RTsymzh][ -O<level>][ -d<opt>] [iCtarget ...]' >&2
    echo 'Must be executed in the iC development environment or one of its subdirectories.' >&2
    echo 'Makes a dedicated icr or ict compiler with integrated arithmetic functions' >&2
    echo 'from iCtarget if iCtarget has arithmetic variables or literal blocks. ' >&2
    echo '	-R	uses icr -c to make a dedicated icr for each iCtarget' >&2
    echo '		output the listings produced to directory ListR' >&2
    echo '	-r	make icr with YYDEBUG -t trace output possible' >&2
    echo '	-T	uses ict -c to make a dedicated ict for each iCtarget' >&2
    echo '		output the listings produced to directory ListT' >&2
    echo '	-t	make ict with YYDEBUG -t trace output possible (default)' >&2
    echo '	-g	each expression has its own C code for debugging with gdb' >&2
    echo '		makeAll with -g option to generate debug binaries' >&2
    echo '	-O <level> optimisation -O0 none -O1 bit -O2 arithmetic -O4 eliminate' >&2
    echo '		duplicate arithmetic expressions -O7 all (default)' >&2
    echo '	-s	make with -DINT_MAX=32767 (make clean; makeAll first)' >&2
    echo '		(on a 16 bit system INT_MAX is 32767 and -s is not required)' >&2
    echo '		simulates compilation for a 16 bit system, which does' >&2
    echo '		no 32 bit arithmetic and rejects QL.. and IL.. I/O unless' >&2
    echo '	-y	make with -DLONG16        (make clean; makeAll first)' >&2
    echo '		produces code for long int arithmetic on a 16 bit system' >&2
    echo '	-d<opt>	call ic[rt] with extra -d<opt> orred into normal -d474' >&2
    echo 'if no iCtargets are specified, each single entry of file po.lt is made' >&2
    echo '   outputs the common output to ListR/Init.out or ListT/Init.out' >&2
    echo '   restores a plain icr or ict at the end of the test run' >&2
    echo '	-m	make each entry from pm.lt instead of default po.lt (takes longer)' >&2
    echo '	-z	echo compiler calls with all options for debugging' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: mo,v 1.22 2008/08/08 19:33:06 jw Exp $' >&2
}

v=""
ic='ict'
op='Tt'
g=''
p='T'
list='po.lt'
z=0

while getopts ":RrTtmsyd:gO:zh" opt; do
    case $opt in
    R )	ic='icr';op='R';p='R';;
    r )	ic='icr';op='Rr';p='R';;
    T )	ic='ict';op='T';p='T';;
    t )	ic='ict';op='Tt';p='T';;
    m )	list='pm.lt';;
    s )	op="${op}s";;
    y )	op="${op}y";;
    d ) v="$v -d$OPTARG";;
    g )	v="$v -g";g="g";;
    O )	v="$v -O$OPTARG";;
    z )	z=1;op="${op}z";;
    h )	usage; exit 0;;
    \?)	echo "$name: illegal option '-$OPTARG'"; usage; exit 127;;
    esac
done
shift $(($OPTIND - 1))

op="$op$g"
devp=$(pwd)
while [ -n "$devp" ]; do
    if [ -x $devp/$ic ]; then
	break				# iC compiler found
    fi
    newp=${devp%/*}
    if [ "$newp" = "$devp" ]; then
	break				# in case of C: in Windows
    fi
    devp=$newp
done
if [ ! -x $devp/$ic ]; then
    echo "no '$ic' found in '$(pwd)' or one of its subdirectories" >&2
    echo "maybe you need to make '$ic' first ???" >&2
    exit 254
fi

rm -f /tmp/cexe.c			# just in case
$ic -c < /dev/null			# uses installed iC compiler
mv cexe.c /tmp				# empty cexe.c for comparison

if [ $# -ne 0 ]; then
    test -d List$p || mkdir List$p;
    for f in $*; do
	file=$f
	base=${file%.*}
	file="$base.ic"
	if [ -f "$file" ]; then
	    if $ic$v -c -d474 -l List$p/$base.lst $file && ! cmp -s cexe.c /tmp/cexe.c; then
		if [ $z -eq 1 ]; then
		    echo "$ic$v -c -d474 -l List$p/$base.lst $file" >&2	# only if different
		fi
		echo "$file";
		cp -f cexe.c List$p/$base.c
		mv -f cexe.c $devp 2> /dev/null
		cd $devp
		rm -f cexe.o $ic	# new cexe.o too soon for make sometimes
		if [ $z -eq 1 ]; then
		    echo "makeAll -$op" >&2
		fi
		makeAll -$op 2>&1 | if [ $z -ne 1 ]; then  grep -iE '(error|warning|:[0-9]+:)'; else cat; fi
		cd - > /dev/null
		if [ -x $devp/$ic ]; then	# use newly generated compiler
		    if [ $z -eq 1 ]; then
			echo "$devp/$ic$v -d500 $file > List$p/$base.ini" >&2
		    fi
		    $devp/$ic$v -d500 $file > List$p/$base.ini
		else
		    echo "make $ic from $file failed"
		fi
	    else
		rm -f List$p/$base.lst	# only keep listings with functions or literals
		if [ $z -eq 1 ]; then
		    echo "$ic has no functions or literals - standard cexe.c" >&2
		fi
	    fi
	else
	    echo "ERROR: $file does not exist - no $ic made"
	fi
    done
elif [ -f $list ]; then
    test -d List$p || mkdir List$p;
    for f in $(cat $list); do
	file=$f
	base=${file%.*}
	file="$base.ic"
	if [ -f "$file" ]; then
	    if $ic$v -c -d474 -l List$p/$base.lst $file && ! cmp -s cexe.c /tmp/cexe.c; then
		if [ $z -eq 1 ]; then
		    echo "$ic$v -c -d474 -l List$p/$base.lst $file" >&2	# only if different
		fi
		echo "$file";
		cp -f cexe.c List$p/$base.c
		mv -f cexe.c $devp 2> /dev/null
		cd $devp
		rm -f cexe.o $ic	# new cexe.c too soon for make sometimes
		if [ $z -eq 1 ]; then
		    echo "makeAll -$op" >&2
		fi
		makeAll -$op 2>&1 | if [ $z -ne 1 ]; then  grep -iE '(error|warning|:[0-9]+:)'; else cat; fi
		cd - > /dev/null
		if [ -x $devp/$ic ]; then	# use newly generated compiler
		    if [ $z -eq 1 ]; then
			echo "$devp/$ic$v -d500 $file > List$p/$base.ini" >&2
		    fi
		    $devp/$ic$v -d500 $file > List$p/$base.ini
		else
		    echo "make $ic from $file failed"
		fi
	    else
		rm -f List$p/$base.lst	# only keep listings with functions or literals
		if [ $z -eq 1 ]; then
		    echo "$ic has no functions or literals - standard cexe.c" >&2
		fi
	    fi
	else
	    echo "ERROR: $file does not exist - no $ic made" >&2
	fi
    done 2>&1 | sed '/^\/tmp\/[a-z_A-Z][a-z_A-Z0-9]*\./ s//\/tmp\/x./' > List$p/Init.out
    if [ -f /tmp/cexe.c ]; then
	cd $devp			# restore plain icr or ict
	cp /tmp/cexe.c .
	rm -f cexe.o $ic		# new cexe.c too soon for make sometimes
	if [ $z -eq 1 ]; then
	    echo "makeAll -$op" >&2
	fi
	makeAll -$op 2>&1 | if [ $z -ne 1 ]; then  grep -iE '(error|warning|:[0-9]+:)'; else cat; fi
	cd - > /dev/null
    fi
else
    echo "ERROR: no list of test iC sources '$list' found - no $ic made" >&2
fi
rm -f /tmp/cexe.c			# clean up in case another user wants to use it
