#!/bin/bash

########################################################################
#
#	make a function version of ict or icc
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-h] [iCtarget ...]' >&2
    echo '      -C	uses icc -c to make a dedicated icc for each iCtarget' >&2
    echo '		output the listings produced to directory ListC' >&2
    echo '      -T	uses ict -c to make a dedicated ict for each iCtarget' >&2
    echo '		output the listings produced to directory ListT' >&2
    echo '		(default option)' >&2
    echo 'if no iCtargets are specified, each single entry of file pm.lt is made' >&2
    echo '   outputs the common output to ListC/Init.out or ListT/Init.out' >&2
    echo '   restores a plain icc or ict at the end of the test run' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: mo,v 1.12 2003/12/29 21:27:45 jw Exp $' >&2
}

ic='ict'
op='T'

while [ $# > 0 ]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [ -n "$option" ]; do
	    case "$option" in
	    C*)	ic='icc';op='C';;
	    T*)	ic='ict';op='T';;
	    h*)	usage; exit 255;;
	    *)	echo "unknown flag -$option";
		usage; exit 255;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

test -d List$op || mkdir List$op;

if [ $# != 0 ]; then
    for f in $*; do
	file=$f
	base=${file%.*}
	if [ "$file" = "$base" ]; then
	    file="$base.ic"
	fi
	if [ -f "$file" ]; then
	    echo "$file";
	    $ic -c -d474 -l List$op/$base.lst $file
	    cp -f cexe.c List$op/$base.c
	    cd ..
	    rm -f cexe.o $ic	# new cexe.o too soon for make sometimes
	    makeAll -$op 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
	    cd - > /dev/null
	    if [[ -f ../$ic ]]; then	# use locally generated compiler
		../$ic -d500 $file > List$op/$base.ini
	    else
		echo make $ic failed
	    fi
	fi
    done
else
    for f in $(cat pm.lt); do
	file=$f
	base=${file%.*}
	if [ "$file" = "$base" ]; then
	    file="$base.ic"
	fi
	if [ -f "$file" ]; then
	    echo "$file";
	    $ic -c -d474 -l List$op/$base.lst $file
	    cp -f cexe.c List$op/$base.c
	    cd ..
	    rm -f cexe.o $ic	# new cexe.c too soon for make sometimes
	    makeAll -$op 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
	    cd - > /dev/null
	    if [[ -f ../$ic ]]; then	# use locally generated compiler
		../$ic -d500 $file > List$op/$base.ini
	    else
		echo make $ic failed
	    fi
	fi
    done > List$op/Init.out 2>&1;
    $ic -c < /dev/null			# restore plain icc or ict
    cd ..
    rm -f cexe.o $ic	# new cexe.c too soon for make sometimes
    makeAll -$op 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
    cd - > /dev/null
fi
