#!/usr/bin/ksh -p

########################################################################
#
#	make OutP in Test icc
#
########################################################################

test -d ListP || mkdir ListP;

if [[ $# != 0 ]]; then
    for f in $*; do
	echo "$f.ic";
	icc -c $f.ic		# listing only with -d474
	cd ..
	rm -f cexe.o icc	# new cexe.o too soon for make sometimes
	make icc 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
	if [[ -f icc ]]; then
	    cd Test		# use locally generated compiler
	    ../icc -d474 -l ListP/$f.lst $f.ic;
	else
	    echo make icc failed
	    cd Test
	fi
    done
else
    for f in $(cat pe.lst); do
	echo "$f.ic";
	icc -c $f.ic		# listing only with -d474
	cd ..
	rm -f cexe.o icc	# new cexe.c too soon for make sometimes
	make icc 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
	if [[ -f icc ]]; then
	    cd Test		# use locally generated compiler
	    ../icc -d474 -l ListP/$f.lst $f.ic;
	else
	    echo make icc failed
	    cd Test
	fi
    done > OutP 2>&1;
fi
