#!/bin/bash

########################################################################
#
#	make OutP in test icc
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-h] [iCtarget ...]' >&2
    echo '	-h	this help text' >&2
    echo 'uses icc -c to make a dedicated icc for each iCtarget' >&2
    echo 'output the listings produced to directory ListP' >&2
    echo 'if no iCtargets are specified, make each line of file pe.lt' >&2
    echo 'in this case also output the common output to OutP' >&2
    echo '	$Id: mp,v 1.9 2003/12/14 06:34:56 jw Exp $' >&2
}

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    h*)	usage; exit 255;;
	    *)	echo "unknown flag -$option";
		usage; exit 255;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

test -d ListP || mkdir ListP;

if [[ $# != 0 ]]; then
    for f in $*; do
	echo "$f.ic";
	icc -c -d474 -l ListP/$f.lst $f.ic
	cp -f cexe.c ListP/$f.c
	cd ..
	rm -f cexe.o icc	# new cexe.o too soon for make sometimes
	makeAll -C 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
	cd - > /dev/null
	if [[ -f ../icc ]]; then	# use locally generated compiler
	    ../icc -d500 $f.ic > ListP/$f.ini
	else
	    echo make icc failed
	fi
    done
else
    for f in $(cat pe.lt); do
	echo "$f.ic";
	icc -c -d474 -l ListP/$f.lst $f.ic
	cp -f cexe.c ListP/$f.c
	cd ..
	rm -f cexe.o icc	# new cexe.c too soon for make sometimes
	makeAll -C 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
	cd - > /dev/null
	if [[ -f ../icc ]]; then	# use locally generated compiler
	    ../icc -d500 $f.ic > ListP/$f.ini
	else
	    echo make icc failed
	fi
    done > OutP 2>&1;
    icc -c < /dev/null			# restore plain icc
    cd ..
    rm -f cexe.o icc	# new cexe.c too soon for make sometimes
    makeAll -C 2>&1 | grep -iE '(error|warning|:[0-9]+:)'
    cd - > /dev/null
fi
