#!/usr/bin/ksh -p

########################################################################
#
#	make versions of icc ict and libict.a
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-dh] [ver ...]' >&2
    echo '	-d	diff icc.v in versions' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: mpv,v 1.2 2002/06/06 08:30:19 jw Exp $' >&2
}

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    d*)	d=diff;;
	    h*)	usage; exit 255;;
	    *) aflag="-$option"; break;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

if [[ $# != 0 ]]; then
    versions=$*
else
    versions=$(echo Test/Alex??)
fi

if [[ -n "$d" ]]; then
    for w in $versions; do
	if [[ ! -L $w ]]; then
	    v=${w##*[a-z]}
	    echo "### $v ###"
	    co -p1.$v icc.v | diff - icc.v_1.$v/icc.v
	fi
    done
    exit
fi

for w in $versions; do
    if [[ ! -L $w ]]; then
	v=${w##*[a-z]}
	echo "### $v ###"
	if [[ ! -d icc.v_1.$v ]]; then
	    cov -r1.$v icc.v
	    cp cexe.c cexe.c_empty y.tab.h icc.v_1.$v
	fi
	cd icc.v_1.$v
	if [[ ! -e makeAll ]]; then ln -s ../makeAll .; fi
	if [[ ! -e makeIct ]]; then ln -s ../makeIct .; fi
	if [[ ! -e makeLib ]]; then ln -s ../makeLib .; fi
	makeAll
	cp icc ../Test/icc$v
	cp ict ../Test/ict$v
	cp libict.a ../Test/libict$v.a
	mkv icc ict libict.a > ../Test/icc$v.v
	cd ..
    fi
done
