#!/usr/bin/ksh -p

########################################################################
#
#	make iC files in previous versions
#
########################################################################

usage ()
{
    echo 'Usage:	'${0##*/}' [-dh] file ...' >&2
    echo '	-d	diff previously made files' >&2
    echo '	-h	this help text' >&2
    echo '	$Id: mz,v 1.7 2002/06/06 08:30:19 jw Exp $' >&2
}

while [[ $# > 0 ]]; do
    case $1 in
    -)	shift; break;;
    -*)	option=${1#?}
	while [[ -n "$option" ]]; do
	    case "$option" in
	    d*)	d=diff;;
	    h*)	usage; exit 255;;
	    *) aflag="-$option"; break;;
	    esac
	    option=${option#?}
	done;;
    *)	break;;
    esac
    shift
done

for f in $*; do
    if [[ ! -e $f.ic ]]; then
	echo "source $f.ic does not exist"
	er=1
    fi
done

if [[ -n "$er" ]]; then
    exit 2;
fi

versions=$(echo Alex??)

for w in $versions; do
    if [[ ! -L $w ]]; then
	v=${w##*[a-z]}
	echo "### $v ###"
	for f in $*; do
	    rm -f $f $f.lst $f.c $f.ini
	    if [[ -z "$d" ]]; then
		rm -f Alex$v/$f.lst Alex$v/$f.c Alex$v/$f.ini
	    fi
	done
	iCmake -v$v $*;
	for f in $*; do
	    if [[ -n "$d" ]]; then
		Mdiff -ne $f.ic $f.lst $f.c $f.ini Alex$v
	    else
		cp $f.ic $f.lst $f.c $f.ini Alex$v
	    fi
	done
    fi
done
