#! /bin/bash
########################################################################
#
#	save execution lists in X100 X101 etc and branchY in Y100_1 etc
#
########################################################################

# $Id: saveX,v 1.1 2007/02/24 10:55:26 jw Exp $

name=${0##*/}
vp='X'		## save directory prefix
vn='100'	## save directory start numeral
wp='Y'		## branch directory prefix
wn='1'		## branch directory start numeral
vpath="$vp*"
n=''

ml
if [ -f pd.lt ]; then
    for d in $vpath; do
	if [ -d $d ]; then
	    nt=${d#$vp*}
	    if [[ $nt =~ '[0-9][0-9]*' ]]; then
		n=$nt
	    else
		echo "**** Warning: $name '$d' must be '$vp' followed by digits, not '$nt' - ignored"
	    fi
	fi
    done
    if [ $name = 'saveX' ]; then
	if [ -z $n ]; then
	    head="$vp$vn"
	    echo "#### $name $head"
	    mkdir $head
	    cp -p $(cat p[d6].lt) $head
	else
	    previous="$vp$n"
	    let n=$n+1
	    head="$vp$n"
	    if ! Mdiff -kLeq $(cat p[d6].lt) $previous; then
		echo "#### $name $head"
		mkdir $head
		cd $head
		ln -s ../$previous/* .
		cd ..
		cp --remove-destination -p $(Mdiff -kLel $(cat p[d6].lt) $head) $head
	    else
		echo "**** Error: $name directory will get no new files - no $head made"
	    fi
	fi
    elif [ $name = 'branchY' ]; then
	head="$vp$n"
	w="$wp${n}_"
	wpath="$w*"
	for db in $wpath; do
	    :	# additional files in head directory are linked below
	done
	if [ $db = "$wpath" ]; then
	    previous=$head	# wpath is empty
	    m="$wn"		# usually 1 - can be 0
	else
	    m=${db#$w*}
	    previous="$w$m"
	    let m=$m+1
	fi
	branch="$w$m"
	if ! Mdiff -kLeq $(cat p[d6].lt) $previous; then
	    echo "#### $name $branch"
	    mkdir $branch
	    cd $branch
	    ln -s ../$head/* .
	    cd ..
	    cp --remove-destination -p $(Mdiff -kLel $(cat p[d6].lt) $branch) $branch
	else
	    echo "**** Error: $name directory will get no new files - no $branch made"
	fi
    else
	echo "**** Error: $name - can only be called with 'saveX' or 'branchY'"
    fi
else
    echo "**** Error: $name - no iC files exist - nothing can be saved"
fi
