#! /bin/bash
# $Id: update,v 1.9 2012/11/15 03:13:19 jw Exp $

name=${0##*/}
vp='V'		## save directory prefix
vn='100'	## save directory start numeral
wp='W'		## branch directory prefix
wn='01'		## branch directory start numeral - range 01 - 99
vpath="$vp*"
n=''
previous=''

if locked -q; then
    for d in $vpath; do
	if [ -d $d ]; then
	    nt=${d#$vp*}
	    if [[ $nt =~ '[^0-9]' ]]; then
		echo "**** Warning: $name '$d' must be '$vp' followed by digits only, not '$nt' - ignored"
	    else
		n=$nt
	    fi
	fi
    done
    if [ $name = 'save' ]; then
	if [ -z $n ]; then
	    head="$vp$vn"
	    echo "#### $name $head"
	    mkdir $head
	    cd $head
	    ln -s ../RCS .
	    cd ..
	    cp -p $(locked) $head
	else
	    previous="$vp$n"
	    let n=$n+1
	    head="$vp$n"
	    if ! Mdiff -wkLeq $(locked) $previous; then
		echo "#### $name $head"
		mkdir $head
		cd $head
		for f in ../$previous/*; do
		    if [ -L $f ]; then
			cp -a $f .
		    elif [ -f $f ]; then
			ln -s $f .
		    else
			echo "**** Error: $name has strange file $f - not backed up"
		    fi
		done
		rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
		cd ..
		cp --remove-destination -p $(Mdiff -wkLel $(locked) $head) $head
	    else
		echo "**** Warning: $name directory will get no new files - no $head made"
	    fi
	fi
    elif [ $name = 'branch' ]; then
	if [ -n $n ]; then
	    head="$vp$n"
	    w="$wp${n}_"
	    wpath="$w*"
	    db=''
	    for d in $wpath; do
		if [ -d $d ]; then
		    db=$d
		fi
	    done
	    if [ -z $db ]; then
		previous=$head	# wpath is empty
		m="$wn"		# usually 01 - can be 00, 0 or 1 (1 - 9 only)
	    else
		m=${db#$w*}
		previous="$w$m"
		j=${m#0}
		if [ $j != $m ]; then
		    let m=$j+1
		    if [ $m != 10 ]; then
			m="0$m"
		    fi
		else
		    let m=$m+1
		fi
	    fi
	    branch="$w$m"
	    if ! Mdiff -wkLeq $(locked) $previous; then
		echo "#### $name $branch"
		mkdir $branch
		cd $branch
		for f in ../$previous/*; do
		    if [ -L $f ]; then
			cp -a $f .
		    elif [ -f $f ]; then
			ln -s $f .
		    else
			echo "**** Error: $name has strange file $f - not backed up"
		    fi
		done
		rm -f $(Mdiff -Lle * ..)	# remove links to files which no longer exist
		cd ..
		cp --remove-destination -p $(Mdiff -wkLel $(locked) $branch) $branch
	    else
		echo "**** Warning: $name directory will get no new files - no $branch made"
	    fi
	else
	    echo "**** Error: $name no 'save' has ever been done - no branch made"
	fi
    fi
else
    echo "**** Error: $name - no files are locked - nothing can be saved"
fi
